In [1]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import matplotlib as plt
import numpy as np

In [2]:
df = pd.read_csv("../data/DBScan/dbscan_clustered_0.17.csv")
df.shape

(1229374, 442)

In [3]:
cluster_modes = df[df['cluster_labels'] != -1].groupby('cluster_labels').agg(pd.Series.mode) # gets the mode of every value, similar to a centriod of kmodes 
cluster_means = df[df['cluster_labels'] != -1].groupby('cluster_labels').mean() #gets the prevalence of a feature per cluster
cluster_amount = len(set(df[df['cluster_labels'] != -1]["cluster_labels"]))
print("shape: ", df[df["cluster_labels"] != -1].shape)
print("number of clusters: ", cluster_amount)

shape:  (1220444, 442)
number of clusters:  8

In [4]:
cluster_modes.iloc[:,:5]

,properties_images,properties_notes,properties_orientation_data,properties_name,geometry_type
cluster_labels,,,,,
0,0.0,0.0,0.0,1.0,1.0
1,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,1.0,1.0
3,0.0,1.0,1.0,1.0,1.0
4,0.0,0.0,0.0,1.0,1.0
5,0.0,0.0,0.0,1.0,1.0
6,0.0,1.0,0.0,1.0,1.0
7,0.0,0.0,0.0,1.0,1.0

In [5]:
for cluster in cluster_modes.index:
    print(f"Cluster {cluster}: {df[df["cluster_labels"] == cluster].shape}")

Cluster 0: (1183288, 442)
Cluster 1: (12537, 442)
Cluster 2: (1359, 442)
Cluster 3: (6612, 442)
Cluster 4: (2991, 442)
Cluster 5: (7962, 442)
Cluster 6: (2307, 442)
Cluster 7: (3388, 442)

In [13]:
discriminating_features = []

for col in cluster_modes.columns:
    temp = set()
    for cluster in cluster_modes[col]:
        temp.add(cluster)
        
    if len(temp) > 1:
        discriminating_features.append(col)
       
print(f"{len(discriminating_features)} Discriminating Features: ") 
for feature in discriminating_features:
    print(f"\t{feature}")

51 Discriminating Features:
	properties_notes
	properties_orientation_data
	geometry_type
	geometry_coordinates
	properties_trace_trace_feature
	properties_trace_trace_quality
	properties_trace_trace_type
	properties_trace_contact_type
	properties_trace_intrusive_contact_type
	properties_other_features
	properties_orientation_type
	properties_orientation_strike
	properties_orientation_dip_direction
	properties_orientation_dip
	properties_orientation_label
	properties_orientation_quality
	properties_orientation_feature_type
	properties_rock_unit_unit_label_abbreviation
	properties_rock_unit_rock_type
	properties_custom_fields_Station
	properties_custom_fields_STATNUM
	properties_custom_fields_VARIANT
	properties_custom_fields_GENERATION
	properties_custom_fields_UTMX
	properties_custom_fields_UTMY
	properties_custom_fields_OBJECTID
	properties_custom_fields_AREA
	properties_custom_fields_PERIMETER
	properties_custom_fields_GEO_
	properties_custom_fields_GEO_ID
	properties_custom_fields_GEO_TYPE
	properties_custom_fields_GEO_SYM
	properties_custom_fields_GEO_LINK
	properties_custom_fields_CODE
	properties_custom_fields_Colour
	properties_custom_fields_Grouping
	properties_custom_fields_Shape_Leng
	properties_custom_fields_Shape_Area
	properties_custom_fields_PlateID
	properties_custom_fields_Terrane(s)
	properties_custom_fields_GEO_PAT
	properties_custom_fields_GEO_MISC
	properties_custom_fields_quality
	properties_custom_fields_type
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_epoch
	properties_rock_unit_group_unit_type
	properties_custom_fields_gid
	properties_custom_fields_state
	properties_custom_fields_county

In [7]:
print(cluster_means[discriminating_features])

                properties_notes  properties_orientation_data  geometry_type  \
cluster_labels
0                       0.201990                     0.315801            1.0
1                       0.044109                     0.411103            0.0
2                       0.109639                     0.058131            1.0
3                       1.000000                     1.000000            1.0
4                       0.000000                     0.000000            1.0
5                       0.392615                     0.000000            1.0
6                       1.000000                     0.000000            1.0
7                       0.039256                     0.000000            1.0

                geometry_coordinates  properties_trace_trace_feature  \
cluster_labels
0                                1.0                        0.035728
1                                0.0                        0.000000
2                                1.0                        0.000000
3                                1.0                        0.000000
4                                1.0                        0.000000
5                                1.0                        0.000000
6                                1.0                        0.000000
7                                1.0                        1.000000

                properties_trace_trace_quality  properties_trace_trace_type  \
cluster_labels
0                                      0.02674                     0.035321
1                                      0.00000                     0.000000
2                                      0.00000                     0.000000
3                                      0.00000                     0.000000
4                                      0.00000                     0.000000
5                                      0.00000                     0.000000
6                                      0.00000                     0.000000
7                                      1.00000                     1.000000

                properties_trace_contact_type  \
cluster_labels
0                                    0.009883
1                                    0.000000
2                                    0.000000
3                                    0.000000
4                                    0.000000
5                                    0.000000
6                                    0.000000
7                                    0.983176

                properties_trace_intrusive_contact_type  \
cluster_labels
0                                              0.000570
1                                              0.000000
2                                              0.000000
3                                              0.000000
4                                              0.000000
5                                              0.000000
6                                              0.000000
7                                              0.983176

                properties_other_features  ...  \
cluster_labels                             ...
0                                0.067295  ...
1                                0.274468  ...
2                                0.000000  ...
3                                0.999849  ...
4                                0.000000  ...
5                                0.000000  ...
6                                0.000000  ...
7                                0.000000  ...

                properties_custom_fields_GEO_MISC  \
cluster_labels
0                                        0.000000
1                                        0.000000
2                                        0.000000
3                                        0.000000
4                                        0.532263
5                                        0.000000
6                                        0.000000
7                                        0.000000

                properties_custom_fields_quality  \
cluster_labels
0                                       0.023737
1                                       0.000000
2                                       0.000000
3                                       0.000000
4                                       0.000000
5                                       0.000000
6                                       0.000000
7                                       0.719894

                properties_custom_fields_type  properties_rock_unit_era  \
cluster_labels
0                                    0.005824                  0.000201
1                                    0.000000                  0.000000
2                                    0.000000                  0.000000
3                                    0.000000                  0.000000
4                                    0.000000                  0.000000
5                                    0.000000                  1.000000
6                                    0.000000                  0.000000
7                                    1.000000                  0.000000

                properties_rock_unit_period  properties_rock_unit_epoch  \
cluster_labels
0                                  0.000200                    0.000000
1                                  0.000000                    0.000000
2                                  0.000000                    0.000000
3                                  0.000000                    0.000000
4                                  0.000000                    0.000000
5                                  0.922507                    0.697312
6                                  0.000000                    0.000000
7                                  0.000000                    0.000000

                properties_rock_unit_group_unit_type  \
cluster_labels
0                                           0.000000
1                                           0.000000
2                                           0.000000
3                                           0.000000
4                                           0.000000
5                                           0.613539
6                                           0.000000
7                                           0.000000

                properties_custom_fields_gid  properties_custom_fields_state  \
cluster_labels
0                                        0.0                             0.0
1                                        0.0                             0.0
2                                        0.0                             0.0
3                                        0.0                             0.0
4                                        0.0                             0.0
5                                        0.0                             0.0
6                                        1.0                             1.0
7                                        0.0                             0.0

                properties_custom_fields_county
cluster_labels
0                                           0.0
1                                           0.0
2                                           0.0
3                                           0.0
4                                           0.0
5                                           0.0
6                                           1.0
7                                           0.0

[8 rows x 51 columns]

In [8]:
global_mean = df[df['cluster_labels'] != -1].drop(columns='cluster_labels').mean() # presence in the entire dataset
deviation = cluster_means[discriminating_features] / global_mean[discriminating_features]

deviation

,properties_notes,properties_orientation_data,geometry_type,geometry_coordinates,properties_trace_trace_feature,properties_trace_trace_quality,properties_trace_trace_type,properties_trace_contact_type,properties_trace_intrusive_contact_type,properties_other_features,...,properties_custom_fields_GEO_MISC,properties_custom_fields_quality,properties_custom_fields_type,properties_rock_unit_era,properties_rock_unit_period,properties_rock_unit_epoch,properties_rock_unit_group_unit_type,properties_custom_fields_gid,properties_custom_fields_state,properties_custom_fields_county
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0.978662,0.999712,1.010379,1.010379,0.954878,0.931644,0.954062,0.802742,0.173788,0.915795,...,0.000000,0.948995,0.691480,0.029936,0.032240,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.213715,1.301406,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.735154,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.531215,0.184022,1.010379,1.010379,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4.845108,3.165643,1.010379,1.010379,0.000000,0.000000,0.000000,0.000000,0.000000,13.606666,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,1.010379,1.010379,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,408.038783,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,1.902262,0.000000,1.010379,1.010379,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,148.834634,148.492221,153.283597,153.283597,0.000000,0.000000,0.000000
6,4.845108,0.000000,1.010379,1.010379,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,529.017772,529.017772,529.017772
7,0.190201,0.000000,1.010379,1.010379,26.726026,34.840960,27.011133,79.860975,299.528494,0.000000,...,0.000000,28.780751,118.720233,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [9]:
significant_deviations = {}
cluster_defining_features = {}

for cluster in deviation.index:
    features = deviation.loc[cluster]
    significant = features[features >= 2].sort_values(ascending=False)
    significant_deviations[cluster] = significant

for cluster, features in significant_deviations.items():
    print(f"\nCluster {cluster} : {df[df["cluster_labels"] == cluster].shape[0]} samples")
    if len(features) == 0:
        print("\tNo significant features")
        cluster_defining_features[cluster] = []
    else:
        temp = []
        for feature, ratio in features.items():
            # print(f"\t{feature}: {ratio:.2f}x more present in cluster")
            print(f"\t{feature}")
            temp.append(feature)
        cluster_defining_features[cluster] = temp

Cluster 0 : 1183288 samples
	No significant features

Cluster 1 : 12537 samples
	properties_other_features

Cluster 2 : 1359 samples
	properties_orientation_quality
	properties_orientation_type
	properties_orientation_strike
	properties_orientation_dip_direction
	properties_orientation_dip
	properties_orientation_label
	properties_orientation_feature_type

Cluster 3 : 6612 samples
	properties_custom_fields_UTMX
	properties_custom_fields_UTMY
	properties_custom_fields_GENERATION
	properties_custom_fields_VARIANT
	properties_custom_fields_Station
	properties_custom_fields_STATNUM
	properties_other_features
	properties_notes
	properties_orientation_data

Cluster 4 : 2991 samples
	properties_custom_fields_GEO_MISC
	properties_custom_fields_PlateID
	properties_custom_fields_PERIMETER
	properties_custom_fields_GEO_
	properties_custom_fields_GEO_ID
	properties_custom_fields_GEO_TYPE
	properties_custom_fields_GEO_SYM
	properties_custom_fields_GEO_LINK
	properties_custom_fields_GEO_PAT
	properties_custom_fields_Colour
	properties_custom_fields_Grouping
	properties_custom_fields_Terrane(s)
	properties_custom_fields_CODE
	properties_custom_fields_Shape_Area
	properties_custom_fields_AREA
	properties_custom_fields_OBJECTID
	properties_custom_fields_Shape_Leng

Cluster 5 : 7962 samples
	properties_rock_unit_group_unit_type
	properties_rock_unit_epoch
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_rock_type
	properties_rock_unit_unit_label_abbreviation

Cluster 6 : 2307 samples
	properties_custom_fields_gid
	properties_custom_fields_state
	properties_custom_fields_county
	properties_notes

Cluster 7 : 3388 samples
	properties_trace_intrusive_contact_type
	properties_custom_fields_type
	properties_trace_contact_type
	properties_trace_trace_quality
	properties_custom_fields_quality
	properties_trace_trace_type
	properties_trace_trace_feature

In [10]:
deviation[deviation.index == 0]

,properties_notes,properties_orientation_data,geometry_type,geometry_coordinates,properties_trace_trace_feature,properties_trace_trace_quality,properties_trace_trace_type,properties_trace_contact_type,properties_trace_intrusive_contact_type,properties_other_features,...,properties_custom_fields_GEO_MISC,properties_custom_fields_quality,properties_custom_fields_type,properties_rock_unit_era,properties_rock_unit_period,properties_rock_unit_epoch,properties_rock_unit_group_unit_type,properties_custom_fields_gid,properties_custom_fields_state,properties_custom_fields_county
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0.978662,0.999712,1.010379,1.010379,0.954878,0.931644,0.954062,0.802742,0.173788,0.915795,...,0.0,0.948995,0.69148,0.029936,0.03224,0.0,0.0,0.0,0.0,0.0

In [16]:
def val_count(data):
    counter = 0
    for i in data.columns:
        
        # if i in ["properties_viewed_timestamp" ,"properties_modified_timestamp","properties_symbology_circleColor","properties_id","properties_symbology_lineColor","properties_symbology_lineWidth","properties_symbology_lineDasharray","properties_sed_strat_section_strat_section_id","properties_strat_section_id","properties_symbology_fillColor","properties_orientation_id","properties_custom_fields_osm_id","properties_orientation_modified_timestamp","properties_custom_fields_id","properties_orientation_unix_timestamp","properties_gps_accuracy","properties_altitude","properties_notesTimestamp"]: 
        
        print(counter)
        print(data[i].value_counts())
        counter += 1
        print("=========================="*5)
    print(data.shape)
    
val_count( df[df["cluster_labels"] == 0])

0
properties_images
0.0    1039086
1.0     144202
Name: count, dtype: int64
==================================================================================================================================
1
properties_notes
0.0    944276
1.0    239012
Name: count, dtype: int64
==================================================================================================================================
2
properties_orientation_data
0.0    809605
1.0    373683
Name: count, dtype: int64
==================================================================================================================================
3
properties_name
1.0    1181168
0.0       2120
Name: count, dtype: int64
==================================================================================================================================
4
geometry_type
1.0    1183288
Name: count, dtype: int64
==================================================================================================================================
5
geometry_coordinates
1.0    1183288
Name: count, dtype: int64
==================================================================================================================================
6
properties_samples
0.0    1153058
1.0      30230
Name: count, dtype: int64
==================================================================================================================================
7
properties_altitude_accuracy
0.0    1162839
1.0      20449
Name: count, dtype: int64
==================================================================================================================================
8
properties_lng
0.0    1159917
1.0      23371
Name: count, dtype: int64
==================================================================================================================================
9
properties_image_basemap
0.0    1156726
1.0      26562
Name: count, dtype: int64
==================================================================================================================================
10
properties_lat
0.0    1159918
1.0      23370
Name: count, dtype: int64
==================================================================================================================================
11
properties__3d_structures
0.0    1179147
1.0       4141
Name: count, dtype: int64
==================================================================================================================================
12
properties_trace_trace_feature
0.0    1141011
1.0      42277
Name: count, dtype: int64
==================================================================================================================================
13
properties_trace_trace_quality
0.0    1151647
1.0      31641
Name: count, dtype: int64
==================================================================================================================================
14
properties_trace_trace_type
0.0    1141493
1.0      41795
Name: count, dtype: int64
==================================================================================================================================
15
properties_trace_contact_type
0.0    1171594
1.0      11694
Name: count, dtype: int64
==================================================================================================================================
16
properties_trace_intrusive_contact_type
0.0    1182613
1.0        675
Name: count, dtype: int64
==================================================================================================================================
17
properties_trace_metamorphic_contact_type
0.0    1182802
1.0        486
Name: count, dtype: int64
==================================================================================================================================
18
properties_trace_trace_character
0.0    1179557
1.0       3731
Name: count, dtype: int64
==================================================================================================================================
19
properties_spot_radius
0.0    1169474
1.0      13814
Name: count, dtype: int64
==================================================================================================================================
20
properties_images_notes
0.0    1182188
1.0       1100
Name: count, dtype: int64
==================================================================================================================================
21
properties_sed_strat_section_column_profile
0.0    1183279
1.0          9
Name: count, dtype: int64
==================================================================================================================================
22
properties_sed_strat_section_column_y_axis_units
0.0    1183280
1.0          8
Name: count, dtype: int64
==================================================================================================================================
23
properties_sed_strat_section_purpose
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
24
properties_sed_strat_section_scale_of_interest
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
25
properties_sed_strat_section_obs_interval_bed_obs_scale
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
26
properties_sed_strat_section_section_type
0.0    1183279
1.0          9
Name: count, dtype: int64
==================================================================================================================================
27
properties_sed_strat_section_basin
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
28
properties_sed_strat_section_age
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
29
properties_sed_character
0.0    1175053
1.0       8235
Name: count, dtype: int64
==================================================================================================================================
30
properties_sed_interval_interval_thickness
0.0    1175281
1.0       8007
Name: count, dtype: int64
==================================================================================================================================
31
properties_sed_interval_thickness_units
0.0    1175281
1.0       8007
Name: count, dtype: int64
==================================================================================================================================
32
properties_surface_feature_surface_feature_type
0.0    1163069
1.0      20219
Name: count, dtype: int64
==================================================================================================================================
33
properties_sed_lithologies
0.0    1172955
1.0      10333
Name: count, dtype: int64
==================================================================================================================================
34
properties_sed_strat_section_total_core_length
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
35
properties_sed_bedding_beds
0.0    1180412
1.0       2876
Name: count, dtype: int64
==================================================================================================================================
36
geometry_geometries
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
37
properties_sed_bedding_interbed_proportion_change
0.0    1183282
1.0          6
Name: count, dtype: int64
==================================================================================================================================
38
properties_sed_bedding_interbed_proportion
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
39
properties_sed_bedding_lithology_at_bottom_contact
0.0    1183286
1.0          2
Name: count, dtype: int64
==================================================================================================================================
40
properties_sed_bedding_lithology_at_top_contact
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
41
properties_sed_bedding_package_thickness_units
0.0    1182125
1.0       1163
Name: count, dtype: int64
==================================================================================================================================
42
properties_sed_strat_section_images
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
43
properties_other_features
0.0    1103659
1.0      79629
Name: count, dtype: int64
==================================================================================================================================
44
properties_tephra
0.0    1182613
1.0        675
Name: count, dtype: int64
==================================================================================================================================
45
properties_trace_depositional_contact_type
0.0    1178944
1.0       4344
Name: count, dtype: int64
==================================================================================================================================
46
properties_trace_tace_notes
0.0    1178615
1.0       4673
Name: count, dtype: int64
==================================================================================================================================
47
properties_trace_geologic_structure_type
0.0    1164810
1.0      18478
Name: count, dtype: int64
==================================================================================================================================
48
properties_trace_other_feature
0.0    1170768
1.0      12520
Name: count, dtype: int64
==================================================================================================================================
49
properties_trace_other_other_feature
0.0    1171040
1.0      12248
Name: count, dtype: int64
==================================================================================================================================
50
properties_sed_fossils
0.0    1182932
1.0        356
Name: count, dtype: int64
==================================================================================================================================
51
properties_trace_shear_sense
0.0    1173889
1.0       9399
Name: count, dtype: int64
==================================================================================================================================
52
properties_trace_geomorphic_feature
0.0    1182483
1.0        805
Name: count, dtype: int64
==================================================================================================================================
53
properties_trace_associated_geomorphic_feature
0.0    1183183
1.0        105
Name: count, dtype: int64
==================================================================================================================================
54
properties_trace_landscape_type
0.0    1183251
1.0         37
Name: count, dtype: int64
==================================================================================================================================
55
properties_trace_feature_origin
0.0    1183276
1.0         12
Name: count, dtype: int64
==================================================================================================================================
56
properties_trace_other_structural_zones
0.0    1182791
1.0        497
Name: count, dtype: int64
==================================================================================================================================
57
properties_trace_other_other_structural_zone
0.0    1183074
1.0        214
Name: count, dtype: int64
==================================================================================================================================
58
properties_trace_other_geomorphic_feature
0.0    1183019
1.0        269
Name: count, dtype: int64
==================================================================================================================================
59
properties_trace_other_shear_sense
0.0    1183122
1.0        166
Name: count, dtype: int64
==================================================================================================================================
60
properties_orientation_type
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
61
properties_orientation_strike
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
62
properties_orientation_dip_direction
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
63
properties_orientation_dip
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
64
properties_orientation_label
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
65
properties_orientation_quality
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
66
properties_orientation_feature_type
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
67
properties_pet_rock_type
0.0    1182534
1.0        754
Name: count, dtype: int64
==================================================================================================================================
68
properties_pet_igneous_rock_class
0.0    1183183
1.0        105
Name: count, dtype: int64
==================================================================================================================================
69
properties_pet_volcanic_rock_type
0.0    1183282
1.0          6
Name: count, dtype: int64
==================================================================================================================================
70
properties_pet_occurence_volcanic
0.0    1183284
1.0          4
Name: count, dtype: int64
==================================================================================================================================
71
properties_trace_other_contact_type
0.0    1176939
1.0       6349
Name: count, dtype: int64
==================================================================================================================================
72
properties_trace_antropogenic_feature
0.0    1183252
1.0         36
Name: count, dtype: int64
==================================================================================================================================
73
properties_trace_other_anthropogenic_feature
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
74
properties_surface_feature_other_surface_feature_type
0.0    1183229
1.0         59
Name: count, dtype: int64
==================================================================================================================================
75
properties_trace_other_depositional_type
0.0    1182048
1.0       1240
Name: count, dtype: int64
==================================================================================================================================
76
properties_custom_fields_MIN_AGE
0.0    1180187
1.0       3101
Name: count, dtype: int64
==================================================================================================================================
77
properties_custom_fields_MAX_AGE
0.0    1178005
1.0       5283
Name: count, dtype: int64
==================================================================================================================================
78
properties_trace_fold_type
0.0    1182273
1.0       1015
Name: count, dtype: int64
==================================================================================================================================
79
properties_trace_fold_attitude
0.0    1182889
1.0        399
Name: count, dtype: int64
==================================================================================================================================
80
properties_rock_unit_unit_label_abbreviation
0.0    1176667
1.0       6621
Name: count, dtype: int64
==================================================================================================================================
81
properties_pet_metamorphic_rock_type
0.0    1182674
1.0        614
Name: count, dtype: int64
==================================================================================================================================
82
properties_sed_bedding_package_bedding_trends
0.0    1183283
1.0          5
Name: count, dtype: int64
==================================================================================================================================
83
properties_sed_structures
0.0    1181937
1.0       1351
Name: count, dtype: int64
==================================================================================================================================
84
properties_sed_interpretations
0.0    1183201
1.0         87
Name: count, dtype: int64
==================================================================================================================================
85
properties_pet_protolith
0.0    1183212
1.0         76
Name: count, dtype: int64
==================================================================================================================================
86
properties_pet_texture_volcanic
0.0    1183286
1.0          2
Name: count, dtype: int64
==================================================================================================================================
87
properties_pet_alteration_volcanic
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
88
properties_trace_other_trace_quality
0.0    1181111
1.0       2177
Name: count, dtype: int64
==================================================================================================================================
89
properties_sed_strat_section_section_well_name
0.0    1183288
Name: count, dtype: int64
==================================================================================================================================
90
properties_sed_strat_section_location_locality
0.0    1183288
Name: count, dtype: int64